### ISSUE TITLE
I want to submit a Chinese translation

### ISSUE THREAD

**Issue by lowingly** [OtorisanVardo/SignEdit#1]
This is my first translation for the plugin. I don't know how to submit it. So I submitted it here. This is a Chinese translation. If you need it, please take it.  ^o^

[chs.zip](https://github.com/OtorisanVardo/SignEdit/files/1844551/chs.zip)   <----here

![6tteipn 0 w eac f79lnuy](https://user-images.githubusercontent.com/18659344/37866157-16960c12-2f5d-11e8-8334-b68614f6b0f1.jpg)

**Comment by OtorisanVardo** [comment]
Wow...!
Thank you very much!!!!
